#!/usr/bin/env bash

# Check for required parameters
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi



# Use scp to transfer the file to the user's home directory on the server
scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$2"@"$3":~/
