#!/usr/bin/env bash
# This script is use to display bad luck for the 4th loop
# good luck for the 8th loop iteration
# best school for the other iteration
a=1
while [ $a -lt 11 ]
do
	if [ $a == 4 ]
	then
		echo "Bad luck"
	elif [ $a == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((a++))
done
